name: Validate publiccode.yml

on:
  push:
    paths:
      - "publiccode.yml"
      - ".github/workflows/publiccodeyml-check.yml"
  pull_request:
    paths:
      - "publiccode.yml"
      - ".github/workflows/publiccodeyml-check.yml"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: publiccode.yml validation
    steps:
      - uses: actions/checkout@v4

      - uses: italia/publiccode-parser-action@0deab88c3f094aa12c5826e52ac2c4f176446821 # v1
        with:
          publiccode: "publiccode.yml"
          no-network: true